/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package route.swing.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import route.swing.http.HttpClient;
import route.swing.model.HistoryRoute;
import route.swing.model.user.UserVerificationResponseDto;
import route.swing.util.JsonUtil;

/**
 *
 * @author Luis
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     */
    String[] header = {"Nombre", "Inicio", "Destino"};
    DefaultTableModel model;

    List<HistoryRoute> userRoutes;
    UserVerificationResponseDto user;

    HttpClient client;
    JsonUtil jsonUtil;

    public History(UserVerificationResponseDto user) throws IOException {
        setUndecorated(true);
        initComponents();
        this.user = user;
        setResizable(false);
        setLocationRelativeTo(null);
        model = new DefaultTableModel(header, 0);

        client = new HttpClient();
        jsonUtil = new JsonUtil();

        userRoutes = jsonUtil.fromJsonToList(client.get("/api/user/" + user.getId() + "/routes"), HistoryRoute.class);
        for (HistoryRoute route : userRoutes) {
            if (route.getName() == null) {
                route.setName("Uname");
            }
            Object[] row = {route.getName(), route.getStart().getName(), route.getEnd().getName()};

            model.addRow(row);
        }

        Table.setModel(model);
        rowSorter = new TableRowSorter<>(model);
        Table.setRowSorter(rowSorter);

        InicioField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String text = InicioField.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, 1));  // Filtra en la columna "Inicio"
                }
            }

        });
    }

    private DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> rowSorter;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InicioField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        returnLAbel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioField.setBackground(new java.awt.Color(255, 255, 255));
        InicioField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        InicioField.setForeground(new java.awt.Color(204, 204, 204));
        InicioField.setText("Ingrese nombre");
        InicioField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        InicioField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InicioFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InicioFieldFocusLost(evt);
            }
        });
        jPanel1.add(InicioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 260, 50));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 441));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Detalle de ruta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 270, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        datePicker1.setBackground(new java.awt.Color(255, 255, 255));
        datePicker1.setOpaque(false);
        jPanel1.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 260, 50));

        jPanel4.setBackground(new java.awt.Color(85, 110, 230));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 260, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 670, 480));

        jPanel3.setBackground(new java.awt.Color(213, 218, 248));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnLAbel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        returnLAbel.setText("");
        returnLAbel.setFont(new java.awt.Font("Symbols Nerd Font Mono", 0, 18)); // NOI18N
        returnLAbel.setForeground(new java.awt.Color(0, 0, 0));
        returnLAbel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnLAbelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnLAbelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnLAbelMousePressed(evt);
            }
        });
        jPanel2.add(returnLAbel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Historial");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 160, 50));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InicioFieldFocusGained
        // TODO add your handling code here:
        if (InicioField.getText().equals("Ingrese nombre")) {
            InicioField.setText("");
            InicioField.setForeground(Color.black);
        }
    }//GEN-LAST:event_InicioFieldFocusGained

    private void InicioFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InicioFieldFocusLost
        // TODO add your handling code here:
        if (InicioField.getText().equals("")) {
            InicioField.setText("Ingrese nombre");
            InicioField.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_InicioFieldFocusLost

    private void returnLAbelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLAbelMouseEntered
        // TODO add your handling code here:
        returnLAbel.setForeground(Color.red);
    }//GEN-LAST:event_returnLAbelMouseEntered

    private void returnLAbelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLAbelMouseExited
        // TODO add your handling code here:
        returnLAbel.setForeground(Color.black);
    }//GEN-LAST:event_returnLAbelMouseExited

    private void returnLAbelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLAbelMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_returnLAbelMousePressed

    private void customTable() {
        // Eliminar bordes del encabezado y las celdas
        Table.setShowGrid(false);
        Table.setIntercellSpacing(new Dimension(0, 0));

        // Renderizador de celdas personalizado
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Alternar colores de filas
                if (row % 2 == 0) {
                    cell.setBackground(new Color(220, 220, 220)); // Color gris claro
                } else {
                    cell.setBackground(Color.WHITE);
                }

                // Cambiar fuente
                cell.setFont(new Font("Arial", Font.PLAIN, 14));

                // Eliminar bordes de la celda
                ((JComponent) cell).setBorder(null);

                return cell;
            }
        };

        // Aplicar el renderizador personalizado a todas las columnas
        for (int i = 0; i < Table.getColumnCount(); i++) {
            Table.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
        }

        // Personalizar el encabezado de la tabla
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                JLabel headerLabel = new JLabel(value.toString(), JLabel.CENTER);
                headerLabel.setFont(new Font("Arial", Font.PLAIN, 14));
                headerLabel.setOpaque(true);
                headerLabel.setBackground(Color.WHITE);
                headerLabel.setBorder(null);
                return headerLabel;
            }
        };

        Table.getTableHeader().setDefaultRenderer(headerRenderer);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new History(new UserVerificationResponseDto()).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InicioField;
    private javax.swing.JTable Table;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel returnLAbel;
    // End of variables declaration//GEN-END:variables
}
