/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package route.swing.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import route.swing.http.HttpClient;
import route.swing.model.Route;
import route.swing.util.JsonUtil;

/**
 *
 * @author Luis
 */
public class RoutePanel extends javax.swing.JPanel {

    /**
     * Creates new form RoutePanel
     */
    HttpClient client; 
    JsonUtil jsonUtil;
    private List<Route> routes;
    
    MainPanel Main;
    public RoutePanel(MainPanel main) throws IOException {
        initComponents();
        this.Main = main;
        client = new HttpClient();
        jsonUtil = new JsonUtil();
        
        init();
    }

    public void init() throws IOException {
        routes = jsonUtil.fromJsonToList(client.get("/api/routes"), Route.class);
        if (routes != null) {
            for (int i = 0; i < 15; i++) {
                Route route = routes.get(i);
                JButton button = new JButton(route.getName());
                button.addActionListener(new ButtonClickListener(route));
                
                // Configurar la fuente, el fondo y el borde del botón
                button.setFont(new Font("Arial", Font.PLAIN, 18));
                button.setForeground(Color.white);
                button.setBackground(Color.decode("#556EE6"));
                // button.setBorder(new LineBorder(Color.GRAY, 1));
                jPanel1.add(button);
            }
        }
        // Necesitas llamar a revalidate() y repaint() para asegurarte de que los nuevos botones se rendericen correctamente
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private class ButtonClickListener implements ActionListener {
        private Route route;

        public ButtonClickListener(Route route) {
            this.route = route;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            if (route != null) {
                try {
                    Main.RouteLoadMap(route);
                } catch (IOException ex) {
                    Logger.getLogger(RoutePanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("Ruta nula");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(213, 218, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(213, 218, 248));
        jPanel1.setLayout(new java.awt.GridLayout(10, 0));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 270, 350));

        jPanel4.setBackground(new java.awt.Color(213, 218, 248));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Symbols Nerd Font Mono", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(117, 132, 144));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(117, 132, 144));
        jLabel6.setText("Rutas recomendas");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        jPanel5.setBackground(new java.awt.Color(117, 132, 144));
        jPanel5.setPreferredSize(new java.awt.Dimension(290, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        Main.setForm(new MenuPanel(Main.getUser()));
    }//GEN-LAST:event_jLabel5MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
